version: '3.8'

x-app:
  &app
  build:
    args:
      RUBY_VERSION: 3.1.1
    context: .
  depends_on:
    - db
    - redis
  volumes:
    - .:/srv/app:cached
    - bundle:/usr/local/bundle
    - type: tmpfs
      target: /srv/app/tmp/pids/

services:
  db:
    environment:
      POSTGRES_PASSWORD: postgres
    image: postgres:14-alpine
    ports:
      - '5432:5432'
    restart: always
    volumes:
      - postgres:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    ports:
      - '6379:6379'
    restart: always
    volumes:
      - redis:/data

  web:
    <<: *app
    command: rails s -b 0.0.0.0
    ports:
      - '3000:3000'
    stdin_open: true
    tty: true

  worker:
    <<: *app
    command: sidekiq

volumes:
  bundle: null
  postgres: null
  redis: null
